var string;
var number;
var boolean;
var arrNumbers;
var arrString;
string = 'hola';
number = 13;
boolean = true;
arrNumbers = [1, 3, 6];
arrString = ['Hola', 'Adios'];
console.log(string);
console.log(number);
console.log(boolean);
console.log(arrNumbers);
console.log(arrString);
